#====-- .config/alacritty/alacritty.yml  - Terminal Settings ---*- Yaml -*-====#

#====-- Solarised theme - https://git.io/JJjgS ----------------------------====#
colors:
  # Default colors
  primary:
    background: '0xfdf6e3'
    foreground: '0x586e75'

  # Normal colors
  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'

#====-- Font - JetBrains Mono ---------------------------------------------====#
font:
    normal:
        family: JetBrains Mono
        style: Regular
    # TODO: Ligatures
    # https://github.com/alacritty/alacritty/issues/50
    size: 13

#====- Curser shape - | instead of ▇ --------------------------------------====#
cursor:
    style: Beam
    thickness: 0.2

